name: TDA
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.13
  - anyio=4.8.0
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - async-lru=2.0.4
  - attr=2.5.1
  - attrs=25.1.0
  - babel=2.17.0
  - beautifulsoup4=4.13.3
  - binutils=2.43
  - binutils_impl_linux-64=2.43
  - binutils_linux-64=2.43
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.4
  - c-compiler=1.9.0
  - ca-certificates=2025.11.12
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.2
  - certifi=2025.11.12
  - cffi=1.17.1
  - cgal=6.0.1
  - cgal-cpp=6.0.1
  - charset-normalizer=3.4.1
  - cmake=3.31.5
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.3.1
  - cpp-expected=1.1.0
  - cuda=12.8.0
  - cuda-cccl_linux-64=12.8.55
  - cuda-command-line-tools=12.8.0
  - cuda-compiler=12.8.0
  - cuda-crt-dev_linux-64=12.8.61
  - cuda-crt-tools=12.8.61
  - cuda-cudart=12.8.57
  - cuda-cudart-dev=12.8.57
  - cuda-cudart-dev_linux-64=12.8.57
  - cuda-cudart-static=12.8.57
  - cuda-cudart-static_linux-64=12.8.57
  - cuda-cudart_linux-64=12.8.57
  - cuda-cuobjdump=12.8.55
  - cuda-cupti=12.8.57
  - cuda-cupti-dev=12.8.57
  - cuda-cuxxfilt=12.8.55
  - cuda-driver-dev=12.8.57
  - cuda-driver-dev_linux-64=12.8.57
  - cuda-gdb=12.8.55
  - cuda-libraries=12.8.0
  - cuda-libraries-dev=12.8.0
  - cuda-nsight=12.8.55
  - cuda-nvcc=12.8.61
  - cuda-nvcc-dev_linux-64=12.8.61
  - cuda-nvcc-impl=12.8.61
  - cuda-nvcc-tools=12.8.61
  - cuda-nvcc_linux-64=12.8.61
  - cuda-nvdisasm=12.8.55
  - cuda-nvml-dev=12.8.55
  - cuda-nvprof=12.8.57
  - cuda-nvprune=12.8.55
  - cuda-nvrtc=12.8.61
  - cuda-nvrtc-dev=12.8.61
  - cuda-nvtx=12.8.55
  - cuda-nvvm-dev_linux-64=12.8.61
  - cuda-nvvm-impl=12.8.61
  - cuda-nvvm-tools=12.8.61
  - cuda-nvvp=12.8.57
  - cuda-opencl=12.8.55
  - cuda-opencl-dev=12.8.55
  - cuda-profiler-api=12.8.55
  - cuda-runtime=12.8.0
  - cuda-sanitizer-api=12.8.55
  - cuda-toolkit=12.8.0
  - cuda-tools=12.8.0
  - cuda-version=12.8
  - cuda-visual-tools=12.8.0
  - cxx-compiler=1.9.0
  - cycler=0.12.1
  - cyrus-sasl=2.1.27
  - cython=3.0.12
  - dbus=1.13.6
  - debugpy=1.8.12
  - decorator=5.1.1
  - defusedxml=0.7.1
  - double-conversion=3.3.1
  - eigen=3.4.0
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.4
  - fmt=11.0.2
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.56.0
  - fqdn=1.5.1
  - freetype=2.12.1
  - gcc=13.3.0
  - gcc_impl_linux-64=13.3.0
  - gcc_linux-64=13.3.0
  - gds-tools=1.13.0.11
  - git=2.49.0
  - gmp=6.3.0
  - graphite2=1.3.13
  - gudhi=3.10.1
  - gxx=13.3.0
  - gxx_impl_linux-64=13.3.0
  - gxx_linux-64=13.3.0
  - h11=0.14.0
  - h2=4.2.0
  - harfbuzz=10.2.0
  - hpack=4.1.0
  - httpcore=1.0.7
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.6.1
  - importlib_resources=6.5.2
  - iniconfig=2.0.0
  - ipykernel=6.29.5
  - ipython=8.32.0
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.5
  - joblib=1.4.2
  - json5=0.10.0
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.12.0
  - jupyter_server=2.15.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.10
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - kernel-headers_linux-64=3.10.0
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libarchive=3.7.7
  - libblas=3.9.0
  - libboost=1.86.0
  - libboost-devel=1.86.0
  - libboost-headers=1.86.0
  - libboost-python=1.86.0
  - libboost-python-devel=1.86.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.71
  - libcblas=3.9.0
  - libclang-cpp19.1=19.1.7
  - libclang13=19.1.7
  - libcublas=12.8.3.14
  - libcublas-dev=12.8.3.14
  - libcufft=11.3.3.41
  - libcufft-dev=11.3.3.41
  - libcufile=1.13.0.11
  - libcufile-dev=1.13.0.11
  - libcups=2.3.3
  - libcurand=10.3.9.55
  - libcurand-dev=10.3.9.55
  - libcurl=8.12.1
  - libcusolver=11.7.2.55
  - libcusolver-dev=11.7.2.55
  - libcusparse=12.5.7.53
  - libcusparse-dev=12.5.7.53
  - libdeflate=1.23
  - libdrm=2.4.124
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libexpat=2.6.4
  - libffi=3.4.6
  - libgcc=14.2.0
  - libgcc-devel_linux-64=13.3.0
  - libgcc-ng=14.2.0
  - libgcrypt-lib=1.11.0
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libgl=1.7.0
  - libglib=2.82.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=14.2.0
  - libgpg-error=1.51
  - libhwloc=2.11.2
  - libiconv=1.18
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libllvm19=19.1.7
  - liblzma=5.6.4
  - libmamba=2.0.5
  - libnghttp2=1.64.0
  - libnl=3.11.0
  - libnpp=12.3.3.65
  - libnpp-dev=12.3.3.65
  - libnsl=2.0.1
  - libntlm=1.8
  - libnuma=2.0.18
  - libnvfatbin=12.8.55
  - libnvfatbin-dev=12.8.55
  - libnvjitlink=12.8.61
  - libnvjitlink-dev=12.8.61
  - libnvjpeg=12.3.5.57
  - libnvjpeg-dev=12.3.5.57
  - libopenblas=0.3.28
  - libopengl=1.7.0
  - libpciaccess=0.18
  - libpng=1.6.47
  - libpq=17.3
  - libsanitizer=13.3.0
  - libsodium=1.0.20
  - libsolv=0.7.30
  - libsqlite=3.49.1
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-devel_linux-64=13.3.0
  - libstdcxx-ng=14.2.0
  - libsystemd0=257.3
  - libtiff=4.7.0
  - libudev1=257.3
  - libuuid=2.38.1
  - libuv=1.50.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.8.0
  - libxkbfile=1.1.0
  - libxml2=2.13.6
  - libxslt=1.1.39
  - libzlib=1.3.1
  - llvm-openmp=19.1.7
  - lz4-c=1.10.0
  - lzo=2.10
  - mamba=2.0.5
  - markupsafe=3.0.2
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.7
  - mistune=3.1.2
  - mpfr=4.2.1
  - munkres=1.1.4
  - mysql-common=9.0.1
  - mysql-libs=9.0.1
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nlohmann_json=3.11.3
  - notebook-shim=0.2.4
  - nsight-compute=2025.1.0.14
  - nspr=4.36
  - nss=3.108
  - numpy=2.2.3
  - ocl-icd=2.3.2
  - opencl-headers=2024.10.24
  - openjpeg=2.5.3
  - openldap=2.6.9
  - openssl=3.6.0
  - overrides=7.7.0
  - packaging=24.2
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pcre2=10.44
  - perl=5.32.1
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pixman=0.44.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.6
  - pluggy=1.5.0
  - pot=0.9.5
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.50
  - psutil=6.1.1
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.19.1
  - pyparsing=3.2.1
  - pyside6=6.8.2
  - pysocks=1.7.1
  - pytest=8.3.4
  - python=3.12.9
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.1
  - python-json-logger=2.0.7
  - python_abi=3.12
  - pytz=2025.1
  - pyyaml=6.0.2
  - pyzmq=26.2.1
  - qhull=2020.2
  - qt6-main=6.8.2
  - rdma-core=56.0
  - readline=8.2
  - referencing=0.36.2
  - reproc=14.2.5.post0
  - reproc-cpp=14.2.5.post0
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rhash=1.4.5
  - rpds-py=0.22.3
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - send2trash=1.8.3
  - setuptools=75.8.0
  - simdjson=3.11.6
  - six=1.17.0
  - sniffio=1.3.1
  - soupsieve=2.5
  - spdlog=1.15.1
  - stack_data=0.6.3
  - sysroot_linux-64=2.17
  - tbb=2022.0.0
  - tbb-devel=2022.0.0
  - terminado=0.18.1
  - threadpoolctl=3.5.0
  - tinycss2=1.4.0
  - tk=8.6.13
  - tomli=2.2.1
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20241206
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - unicodedata2=16.0.0
  - uri-template=1.3.0
  - urllib3=2.2.2
  - wayland=1.23.1
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - wheel=0.45.1
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.43
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.5
  - xorg-libx11=1.8.11
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - yaml=0.2.5
  - yaml-cpp=0.8.0
  - zeromq=4.3.5
  - zipp=3.21.0
  - zstd=1.5.7
  - pip:
      - absl-py==2.3.1
      - arxiv-latex-cleaner==1.0.8
      - deprecated==1.2.18
      - filtration-domination==0.1.0
      - hopcroftkarp==1.2.5
      - jupyterlab-execute-time==3.2.0
      - keopscore==2.2.3
      - metakernel==0.30.2
      - multipers==2.3.5b3
      - networkx==2.3
      - oct2py==5.8.0
      - octave-kernel==0.36.0
      - pandas==2.3.3
      - persim==0.3.7
      - pip==25.3
      - ply==3.11
      - pybind11==2.13.6
      - pykeops==2.2.3
      - regex==2025.11.3
      - ripser==0.6.10
      - shapely==2.0.7
      - smop==0.41
      - tzdata==2025.2
      - websocket-client==1.9.0
      - wrapt==1.17.2
